baseurl = "//updevcamp.com/"
languageCode = "en-us"
title = "UP CSI Devcamp"
pygmentsstyle = "colorful"

[taxonomies]
  tracks = "tracks"
  tracks-desc = "tracks-desc"
  author = "authors"

[params]
  defaultDescription = "CSI Devcamp provides a space and network for motivated students to learn and create awesome stuff"
  defaultKeywords = "Devcamp, UP, CSI, Computer, Science, UP CSI Devcamp, Bootcamp, Mentorship, Mentor, Mentee"
